baseURL: "https://www.horaciomorenom.me/" 
title: Horacio Moreno Montañes
pagination:
  pagerSize: 10
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv.pdf
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Thoughts
          url: thoughts/
          weight: 3
        - name: Keywords
          url: /tags/
          weight: 5


params:
    description: "I am an undergraduate student studying Applied Mathematics and Interdisiplinary Physics."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Horacio Moreno Montañes
          subtitle: "I am Applied and Interdisciplinary Mathematics PhD student at the University of Michigan. I work in computational modeling of plasma using both kinetic and fluid models, in particular solar plasma physics, as well as studying the dynamics of these systems. I focus on developing methods that are both simple and parallelizeable using both CPUs and GPUs for efficient computation. My current work focuses on developing and implementing numerical methods to model the magnetic field in the solar corona. "
          imageUrl: "picture.jpg"
          imageWidth: 350
          imageHeight: 350
          imageTitle: Me!
          buttons:
            - name: CV
              url: cv.pdf
            - name: Projects
              url: projects/
            - name: Thoughts
              url: thoughts/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:hmorenom@umich.edu
        - name: YouTube
          url: https://www.youtube.com/@HoracioMorenoMontanes
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://horaciomorenom.substack.com/
        - name: Twitter
          url: https://twitter.com/horaciomorenom

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Horacio"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
